"""Global cookie store for yt-dlp (shared by every project).

Cookies live in ``data/cookies/cookies.txt`` in Netscape format (what yt-dlp
consumes). You can paste a cookie-editor JSON export or a raw Netscape file; both
are normalised here. Expiry is tracked so the app can warn you before they stop
working. Values are never logged.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app import paths

COOKIES_DIR: Path = paths.DATA / "cookies"
COOKIES_FILE: Path = COOKIES_DIR / "cookies.txt"
META_FILE: Path = COOKIES_DIR / "cookies.meta.json"

_EXPIRING_SOON_DAYS = 7.0

# Cookie names that indicate a genuine logged-in session.
_SESSION_MARKERS = ("SID", "__Secure-1PSID", "__Secure-3PSID", "LOGIN_INFO")


class CookieError(ValueError):
    """Raised when cookie input cannot be parsed."""


@dataclass
class CookieStatus:
    present: bool = False
    count: int = 0
    session_cookies: int = 0
    authenticated: bool = False
    updated: str | None = None
    source: str | None = None
    earliest_expiry: float | None = None
    days_left: float | None = None
    expired: bool = False
    expiring_soon: bool = False
    warnings: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "present": self.present,
            "count": self.count,
            "session_cookies": self.session_cookies,
            "authenticated": self.authenticated,
            "updated": self.updated,
            "source": self.source,
            "earliest_expiry": self.earliest_expiry,
            "days_left": None if self.days_left is None else round(self.days_left, 1),
            "expired": self.expired,
            "expiring_soon": self.expiring_soon,
            "warnings": self.warnings,
        }


# --- conversion -----------------------------------------------------------
def from_json(text: str) -> str:
    """Convert a cookie-editor JSON export to Netscape format."""
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise CookieError(f"Not valid JSON: {exc}") from exc
    if isinstance(data, dict) and "cookies" in data:
        data = data["cookies"]
    if not isinstance(data, list):
        raise CookieError("Expected a JSON array of cookies")

    lines = ["# Netscape HTTP Cookie File", "# Generated by Clipper"]
    for item in data:
        if not isinstance(item, dict) or "name" not in item or "domain" not in item:
            continue
        domain = str(item["domain"])
        include_sub = "FALSE" if item.get("hostOnly") else "TRUE"
        path = str(item.get("path", "/"))
        secure = "TRUE" if item.get("secure") else "FALSE"
        if item.get("session") or item.get("expirationDate") is None:
            expiry = "0"
        else:
            try:
                expiry = str(int(float(item["expirationDate"])))
            except (TypeError, ValueError):
                expiry = "0"
        name = str(item["name"])
        value = str(item.get("value", ""))
        lines.append("\t".join([domain, include_sub, path, secure, expiry, name, value]))
    return "\n".join(lines) + "\n"


def from_netscape(text: str) -> str:
    """Validate / normalise an already-Netscape-format cookie file."""
    out = ["# Netscape HTTP Cookie File", "# Generated by Clipper"]
    for raw in text.splitlines():
        line = raw.rstrip("\r\n")
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 7:
            parts = line.split()
        if len(parts) != 7:
            continue
        out.append("\t".join(parts))
    if len(out) <= 2:
        raise CookieError("No valid cookie lines found")
    return "\n".join(out) + "\n"


def parse_any(text: str) -> str:
    """Accept JSON or Netscape and return normalised Netscape content."""
    stripped = text.lstrip("\ufeff \t\r\n")
    if stripped.startswith("[") or stripped.startswith("{"):
        return from_json(stripped)
    return from_netscape(text)


# --- persistence ----------------------------------------------------------
def save(content: str, source: str = "paste") -> CookieStatus:
    COOKIES_DIR.mkdir(parents=True, exist_ok=True)
    COOKIES_FILE.write_text(content, encoding="utf-8")
    meta = {"updated": _now_iso(), "source": source}
    META_FILE.write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return status()


def clear() -> CookieStatus:
    for path in (COOKIES_FILE, META_FILE):
        path.unlink(missing_ok=True)
    return status()


def import_text(text: str, source: str = "paste") -> CookieStatus:
    return save(parse_any(text), source=source)


def store_path() -> Path | None:
    """Path to the cookie file if it exists (for yt-dlp ``--cookies``)."""
    return COOKIES_FILE if COOKIES_FILE.exists() else None


def is_ready() -> bool:
    """True when cookies exist, look authenticated and are not expired."""
    st = status()
    return bool(st.present and st.authenticated and not st.expired)


# --- status ---------------------------------------------------------------
def _read_meta() -> dict[str, Any]:
    if META_FILE.exists():
        try:
            return json.loads(META_FILE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def status() -> CookieStatus:
    st = CookieStatus()
    if not COOKIES_FILE.exists():
        st.warnings.append("No cookies configured — gated or age-restricted videos may fail.")
        return st

    st.present = True
    meta = _read_meta()
    st.updated = meta.get("updated")
    st.source = meta.get("source")

    now = time.time()
    expiries: list[float] = []
    names: list[str] = []
    try:
        for line in COOKIES_FILE.read_text(encoding="utf-8", errors="replace").splitlines():
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != 7:
                continue
            names.append(parts[5])
            try:
                expiry = float(parts[4])
            except ValueError:
                continue
            if expiry > 0:
                expiries.append(expiry)
    except OSError as exc:
        st.warnings.append(f"Could not read cookie file: {exc}")
        return st

    st.count = len(names)
    st.session_cookies = sum(1 for n in names if n in _SESSION_MARKERS)
    st.authenticated = st.session_cookies >= 2

    if expiries:
        earliest = min(expiries)
        st.earliest_expiry = earliest
        st.days_left = (earliest - now) / 86400.0
        st.expired = st.days_left <= 0
        st.expiring_soon = 0 < st.days_left <= _EXPIRING_SOON_DAYS

    if st.expired:
        st.warnings.append("Cookies have expired — re-import them in Settings.")
    elif st.expiring_soon:
        st.warnings.append(f"Cookies expire in {st.days_left:.1f} days.")
    if not st.authenticated:
        st.warnings.append(
            "Cookies look unauthenticated (no YouTube session cookies found). "
            "Sign in to YouTube before exporting."
        )
    return st


def _now_iso() -> str:
    from datetime import datetime

    return datetime.now().isoformat(timespec="seconds")


def ytdlp_args() -> list[str]:
    """yt-dlp args for the global cookie store (empty when unavailable)."""
    path = store_path()
    return ["--cookies", str(path)] if path else []
